version: '3.9'

services:
  db:
    env_file:
      - .env
    container_name: pg_db
    image: postgres:14.3-alpine
    ports:
      - "${PG_PORT}:${PG_PORT}"
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DBNAME}

  pgadmin:
    env_file:
      - .env
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: artemy@artemy.com
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - "5050:80"
